# Generated by Django 3.1.7 on 2021-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0002_auto_20210406_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, verbose_name='ISBN number'),
        ),
    ]
